### ISSUE TITLE
[어드민] 1차 어드민 - 전체 작업

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#100]
### 1차 어드민 작업 필요 목록

서버는 완료된 것으로 알고 있습니다~!

**로그인 뷰**

https://github.com/Dumbs-app/Dumbs_phase2/issues/43

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3377-145023&node-type=frame&t=rdO9ijp7sgMDetvL-11

회원가입 필요 없이
저희끼리 이메일로 로그인합니당

**가게 입점 요청**

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3377-253831&node-type=frame&t=rdO9ijp7sgMDetvL-11

지역 선택

https://github.com/Dumbs-app/Dumbs_phase2/issues/42

로고 업로드 뷰

https://github.com/Dumbs-app/Dumbs_phase2/issues/17
(디자인 변경됨, 하단 댓글 참고 부탁드립니다)

**Comment by Dumbs-app** [comment]
@heyman333 님
#42 지역선택, 로고 업로드 뷰 쪽만 작업해주시면 될 것 같습니다~!

**Comment by Dumbs-app** [comment]
로고 업로드 뷰 작업만 남은 걸로 보여서 #42 에서 이어 진행하겠습니다~
