### ISSUE TITLE
[App][iOS] 공연탭 1차 개선

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#104]
### 개선배경
- 지난 공연을 볼 수 있도록 개편하고자 함
- 기존처럼 버블 드랍다운으로는 이전 달까지 전부 표시해주면 너무 길어지기 때문에 데이트피커를 도입하고자 함

![Image](https://github.com/user-attachments/assets/a10c0d22-7427-4754-b165-94261635682d)

@somedd 님 [가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4430-15316&t=nkvGa0IgI0GSMVzA-1) 전달드립니다!

**Comment by somedd** [comment]
@Dumbs-app  1.1.5에서 반영됩니다 :)

**Comment by somedd** [comment]
@Dumbs-app  1.1.7에서 반영됩니다~!

**Comment by Dumbs-app** [comment]
@somedd 님~~
디자인 수정사항 전달드리니다!
[24.11.30. ios.pdf](https://github.com/user-attachments/files/17965836/24.11.30.ios.pdf)
![Image](https://github.com/user-attachments/assets/70dffa7f-5f21-4a07-83db-fd6ce31480b7)
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4715-17611&t=wd6L7dDzZWrntCNo-1
