### ISSUE TITLE
[App][iOS] 업체상세/공연상세 디자인 수정

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#109]
@somedd 님
업체상세, 공연상세 관련 디자인 수정사항 전달드립니다!
폰트크기 조정과 QA사항입니다 :)
[24.11.14. ios.pdf](https://github.com/user-attachments/files/17748218/24.11.14.ios.pdf)
![Image](https://github.com/user-attachments/assets/a6f846f6-eb67-4485-8a33-f77f1f7e665c)

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4459-13303&t=Ua4kkEqHJDc99xX5-1

**Comment by somedd** [comment]
@Dumbs-app 1.1.5에서 반영됩니다 :)
