### ISSUE TITLE
[App][iOS] 공연상세 디자인 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#112]
![Image](https://github.com/user-attachments/assets/cf4b39d2-e9ff-41e4-8863-e4a10a30318a)
공연상세 페이지 디자인 이슈 전달드립니다. 감사합니다!
@somedd

**Comment by somedd** [comment]
@Dumbs-app  1.1.6버전에 반영됩니다 :)
