### ISSUE TITLE
[어드민] 1차어드민 - 관리용 계정 개설

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#12]
1. 페스티벌 정보 등록: 관리계정 만들기 (업체정보 미등록시에도 작성 가능하게 대응 필요)
2. 업체정보등록 -> 계정넘겨주기 관련 논의 필요

**Comment by txtart** [comment]
추석 연휴 작업예정

**Comment by Dumbs-app** [comment]
@txtart 추석 넘 늦는데요..
2번 말고 1번 일정 따로 알려주실 수 있나욤

**Comment by Dumbs-app** [comment]
@txtart 리마인드~~

**Comment by Dumbs-app** [comment]
1. 페스티벌: 가상의 관리자계정(2차어드민) 생성 후 업체목록에서만 히든처리 하는 방식으로 논의함
2. 업체정보: 가게목록과 가게관리자(2차어드민) 계정 분리하여 관리하는 것으로 논의함

따라서 이슈 클로즈 후 해당이슈 아카이브 해두겠습니다~!
