### ISSUE TITLE
[App][iOS] 어텐션 테이블예약하기 버튼 추가

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#122]
![Image](https://github.com/user-attachments/assets/c7098223-bff9-40b3-8e28-0b5842dfe762)

가이드: [Figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4569-30064&t=G7eP8C515HtMpS67-1)

@somedd 님
홍대 어텐션 상세페이지에 테이블 예약하기 버튼 추가 부탁드리겠습니다 :D

**Comment by somedd** [comment]
반영 완료되었습니다 :)
