### ISSUE TITLE
[And] 메뉴를 이미지만 등록한 경우 뷰 추가 필요

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#13]
**AS IS**
- 텍스트메뉴 1개를 필수로 받고 있음

**TO BE**
- 메뉴입력에 대한 허들을 낮추기 위해
이미지로만 등록도 가능하게 하고자 함
- 따라서 이미지만 등록시 뷰 추가가 필요함

**가이드**
<img width="215" alt="스크린샷 2024-08-11 오후 7 36 50" src="https://github.com/user-attachments/assets/37bde779-484e-4061-bb2f-89974515174d">
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3019-13118&t=5p3ksjsh18sP6tJe-1

**Comment by whtjdhks3837** [comment]
30분정도면 작업 가능합니다

**Comment by somedd** [comment]
iOS도 문제 없습니다!

**Comment by somedd** [comment]
@Dumbs-app iOS는 작업 돼서 라벨 빼두었습니다 :)

**Comment by Dumbs-app** [comment]
안드에도 반영된 것으로 확인하여 이슈 클로즈합니다!
