### ISSUE TITLE
[And] 마이페이지 > 입점하기 추가

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#15]
[배경]
앱 배포 후 입점 신청을 늘리기 위해 입점하기를 추가하고자 함
url: https://admin.dumbs.app/login

<img width="268" alt="스크린샷 2024-08-11 오후 8 50 39" src="https://github.com/user-attachments/assets/658b5ffe-d129-42a3-b89f-1d700fb82bc2">

[디자인가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3121-8587&t=5p3ksjsh18sP6tJe-1)

**Comment by Dumbs-app** [comment]
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3121-8587&t=QJ4WKJQwDdB06CfA-1
디자인가이드 업데이트했습니다!
ㅌ

![Image](https://github.com/user-attachments/assets/1dbd7c2c-1b58-4c2a-ab74-b31fea7ac01d)

**Comment by somedd** [comment]
@Dumbs-app iOS는 1.0.1에서 반영되었습니다 :)
