### ISSUE TITLE
[어드민] 비밀번호 재설정 - 업장

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#23]

**Comment by txtart** [comment]
@3d3nch01 피그마 링크좀요

**Comment by Dumbs-app** [comment]
@txtart 요거는 후순위라서 다른것부터 작업해주실 수 있을까욤!!

**Comment by Dumbs-app** [comment]
@3d3nch01 님이 작성해주신 가이드 등록해둡니다!
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3501-113891&node-type=section&t=En9AcAOZSJXzPjQ

**Comment by 3d3nch01** [comment]
@Dumbs-app 이거 어드민/앱 이슈 분리가 필요할 거 같아여 이 이슈는 어드민이 쓸게요! 앱 회원가입 이슈 따로 발행 부탁드려용

**Comment by Dumbs-app** [comment]
@heyman333 @txtart 
[디자인 가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4278-27922&t=6YILGXSMmeWNjjCq-1) 전달드립니다!

리뷰 필요하시면 말씀 주세용.
cc. @3d3nch01

**Comment by Dumbs-app** [comment]
@heyman333 님 디자인QA 사항 전달드립니당~~

### 휴대폰번호 인풋창 
![Image](https://github.com/user-attachments/assets/298122b6-e36d-4a59-ac6b-248b26b3f3a6)
- 우측 업/다운 화살표 제거 부탁드립니다!

### 인증번호 인풋창
![Image](https://github.com/user-attachments/assets/970260e9-0210-433f-ab0b-6358b66da88e)
- 우측 업/다운 화살표 제거 
- 인증번호 6자리 입력 전에는 '인증번호 확인' 버튼 비활성화 처리 필요

### 비밀번호 재설정
![Image](https://github.com/user-attachments/assets/2bf40332-0b2f-457e-82bc-1e76adc54e56)
- 비밀번호, 비밀번호 확인 인풋에 8자 이상 텍스트 입력되지 않은 경우
'비밀번호 변경하기' 버튼 비활성화 필요

**Comment by heyman333** [comment]
@Dumbs-app 수정완료
