### ISSUE TITLE
[어드민] ABOUT 추가

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#26]
[요청배경]
앱 내 업체상세페이지 > NOTICE, TABLE 메뉴 추가를 위해 어드민에도 세팅이 필요합니다.

![Image](https://github.com/user-attachments/assets/b4c12421-a517-4311-b4c5-dc8607dc26b7)

[요청사항]
@3d3nch01 님
NOTICE, TABLE 메뉴 입력 화면 추가 부탁드립니다!

**Comment by Dumbs-app** [comment]
@3d3nch01 님
TABLE은 다음에 가기로 해서
NOTICE 화면만 대응해주심 될것같슴다!
cc. @heyman333 @txtart

**Comment by 3d3nch01** [comment]
![Image](https://github.com/user-attachments/assets/638586c7-b0ff-4416-8d2b-437df7205213)


'Notice'를 업장 소개인 'About'으로 명칭을 바꿉니다. @txtart cc. @Dumbs-app 
어드민: 가게 소개 = 앱: About (기존: Notice)

### Figma

1. 가입 화면

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=1502-58318&node-type=frame&t=sz4GLpbCKQoWVyaF-11

2. 가입 이후 '가게 정보' 화면

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3408-114584&node-type=frame&t=sz4GLpbCKQoWVyaF-11

**Comment by Dumbs-app** [comment]
> ![Image](https://github.com/user-attachments/assets/638586c7-b0ff-4416-8d2b-437df7205213)
> 
> 'Notice'를 업장 소개인 'About'으로 명칭을 바꿉니다. [@txtart](https://github.com/txtart) cc. [@Dumbs-app](https://github.com/Dumbs-app) 어드민: 가게 소개 = 앱: About (기존: Notice)
> 
> ### Figma
> 1. 가입 화면
> 
> https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=1502-58318&node-type=frame&t=sz4GLpbCKQoWVyaF-11
> 
> 2. 가입 이후 '가게 정보' 화면
> 
> https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3408-114584&node-type=frame&t=sz4GLpbCKQoWVyaF-11

@heyman333 영수님도 작업 필요하실것같아서 같이 멘션드립니당~!

**Comment by Dumbs-app** [comment]
요 이슈 영수님도 확인 필요하실것같아서 멘션드려유~~ @heyman333

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 추가 완료!

**Comment by Dumbs-app** [comment]
확인완료! 감사합니다~!
