### ISSUE TITLE
[Server][App] 업체상세 > ABOUT, TABLE 추가

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#27]
[요청배경]
상세페이지에서 더 많은 정보 전달 하기 위함

[요청사항]
![Image](https://github.com/user-attachments/assets/6a759535-390f-4224-bd87-320602be9483)
업체상세 내 NOTICE, TABLE 메뉴 추가 부탁드립니다!
[Figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3197-8642&t=3QeCu65Q3GMB0fgN-1)
@whtjdhks3837 @somedd

**Comment by Dumbs-app** [comment]
Notice 먼저 배포하는 것으로 결정 (9월중 서버까지 완료 목표) @txtart

**Comment by Dumbs-app** [comment]
@whtjdhks3837 @somedd 
Notice -> About으로 타이틀 변경하게 되었으며,
현준님께서 작업 완료해주신 걸로 확인해서
앱 작업 진행 부탁드리겠습니다~!
![Image](https://github.com/user-attachments/assets/bfd56c37-3e7f-4648-a5e0-921ab26e5a03)
[Figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3315-9203&t=Wvy3EQmoPCFJWmtu-1)

**Comment by somedd** [comment]
iOS 1.0.3버전에 notice 반영 cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
@somedd 님
1.0.6버전 기준으로 재확인했는데 notice 노출이 안되고있네요ㅠㅠ (덤즈클럽으로 확인)

**Comment by somedd** [comment]
1.1.0(6) 에서 수정완료! cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
확인 완료하여 클로즈합니당~!
