### ISSUE TITLE
[어드민] 필수 입력 페이지 수정 후 '메뉴 입력하러 가기' 등 다음 플로우 안내하는 버튼 추가하기

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#28]
### 참고

https://github.com/Dumbs-app/Dumbs_QA/issues/77#issuecomment-2337880147

### Figma

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3408-118995&node-type=frame&t=sz4GLpbCKQoWVyaF-11

### 변경 내용

[AS-IS]

'영업시간 및 입장료' 화면에서
'저장하기'버튼 클릭 시
'저장되었습니다' 팝업 노출, 확인 버튼 클릭 시 창 닫힘

[TO-BE]

<img width="352" alt="image" src="https://github.com/user-attachments/assets/512f7612-7ab5-4bfc-94db-4ff61cccfd2b">

'영업시간 및 입장료' 화면에서
'저장하기' 버튼 클릭 시
해당 팝업 노출됩니다.

'메뉴 입력하러 가기' 클릭 시
'메뉴' 페이지로 이동합니다!

**Comment by 3d3nch01** [comment]
@heyman333 영수님 해당 태스크 작업 가능하십니다!

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 수정완료!

**Comment by Dumbs-app** [comment]
@heyman333 님
영업시간 및 입장료 페이지에 적용된것 확인했는데요!
혹시 `가게정보` 페이지에서 `저장하기` 눌렀을때도 동일 팝업 노출 가능하실까요?ㅠㅠ

버튼명만 `메뉴 입력하러가기` -> `영업시간 및 입장료 입력하러가기` 로 변경해서요..!!!
cc. @3d3nch01

**Comment by heyman333** [comment]
@Dumbs-app 넵!

**Comment by heyman333** [comment]
@Dumbs-app 수정완료!

**Comment by Dumbs-app** [comment]
확인완료! 감사합니다
