### ISSUE TITLE
[쿠폰] 노출관련 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#29]
### [테스트환경]
iOS(1.0.1(3)) / Android(app-release.apk) (08.25자)

### [현재이슈]
@txtart 
쿠폰별로 노출 이슈상황 공유드립니다!
![Image](https://github.com/user-attachments/assets/be61c703-12f2-48b7-9f95-4b584bb1cb9b)
https://docs.google.com/spreadsheets/d/1qW0Ufnwkj3xyPEeP4w-KlQy6qo_7c43ANDw999s67TQ/edit?usp=sharing

### [개선방향]
모든 쿠폰이 `상세페이지`, `이벤트>쿠폰혜택` 페이지에서 노출되어야합니다.
홈에는 가장 처음 생성된 쿠폰이 대표로 노출되고 있는 것 같은데, 
**가장 최근에 생성된 쿠폰으로 노출**되는게 좋을 것 같습니다.

cc. @whtjdhks3837 @somedd

**Comment by txtart** [comment]
@Dumbs-app 수정완료

**Comment by Dumbs-app** [comment]
@txtart 님
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug?node-id=3330-8410#942088110
요 코멘트도 확인 한번 해주세요~!
![Image](https://github.com/user-attachments/assets/09599488-d5cd-47dd-8029-4078dd87fb46)

날짜 표기 변경 필요 
- asis: {nnnn-nn-nn} 
- tobe: {nnnn.nn.nn.까지}

**Comment by Dumbs-app** [comment]
확인 완료해서 이슈클로즈합니당~
