### ISSUE TITLE
[iOS]메뉴를 이미지만 등록한 경우 뷰 추가 필요

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#31]
> @Dumbs-app iOS는 작업 돼서 라벨 빼두었습니다 :) 

 _Originally posted by @somedd in [#13](https://github.com/Dumbs-app/Dumbs_phase2/issues/13#issuecomment-2343574105)_

**Comment by Dumbs-app** [comment]
@somedd 
재욱님 혹시 요거 
두번째 이미지 클릭했을때도 
뷰어에서는 첫번째 이미지가 뜨고 있는데,
두번째 이미지로 진입시에는
뷰어에서도 두번째 이미지가 바로 뜨도록 수정 가능하실까요?!

**Comment by somedd** [comment]
> @somedd 재욱님 혹시 요거 두번째 이미지 클릭했을때도 뷰어에서는 첫번째 이미지가 뜨고 있는데, 두번째 이미지로 진입시에는 뷰어에서도 두번째 이미지가 바로 뜨도록 수정 가능하실까요?!

1.0.4에서 반영되었습니다 :) @Dumbs-app

**Comment by Dumbs-app** [comment]
확인완료! 감사합니다~!
