### ISSUE TITLE
[Server][쿠폰] 유효기간 관련 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#34]

**Comment by Dumbs-app** [comment]
### [요청배경]
기본적으로 쿠폰은 다운로드 날로부터 n년 (통상 1년)동안 사용가능한 유효기간이 있어야함
 
### [현재 이슈]
![Image](https://github.com/user-attachments/assets/3d531d3b-0de5-4a7a-a8e4-b683d9e4b988)
상시노출 쿠폰의 경우 시작날짜가 정해져있지 않아서 유효기간이 노출되지 않고있음 (테스트쿠폰3 참조)

### [개선방향]
`다운로드 날짜`로부터 `1년 뒤 DATE` 까지가 유효기간으로 셋팅되면 좋을 것 같음

@txtart

**Comment by Dumbs-app** [comment]
@txtart 요거확인좀용!!~!

**Comment by Dumbs-app** [comment]
@3d3nch01 이거 개발완료되면
어드민에서도 쿠폰 상시노출 쪽에 '최대 1년동안 상시노출된다' 는 내용만 추가 대응해주심 될 것 같아요! 참고부탁드림당

**Comment by Dumbs-app** [comment]
@whtjdhks3837 @somedd 님
현준님한테 확인해보니 Expired date 추가했다고해서, 앱쪽에 대응 부탁드리겠습니다~!

**Comment by whtjdhks3837** [comment]
@Dumbs-app @txtart 유효기간 없는경우 expired 1년치로 셋팅하여 내려줌

**Comment by Dumbs-app** [comment]
@txtart 지금 앱에 쿠폰 유효기간 안뜨고 있는데 확인 부탁드립니다ㅜ

**Comment by Dumbs-app** [comment]
@txtart 
유효기간 노출 안되고있습니다 지금-!

**테스트환경**
ios / 덤즈클럽 `테스트쿠폰`

앱:
![Image](https://github.com/user-attachments/assets/19ab2a49-0764-49bd-b35c-26f9c03d5904)

어드민:
![Image](https://github.com/user-attachments/assets/af267b77-f298-4fe6-998e-428d7c1dfd1e)

**Comment by Dumbs-app** [comment]
앱과 어드민에 반영확인했습니다! 감사합니다
