### ISSUE TITLE
[랜딩] SEO 최적화 진행

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#35]
@heyman333 
영수님 여기서 팔로업 부탁드리겠습니다~!
https://searchadvisor.naver.com/guide/seo-basic-intro

**Comment by Dumbs-app** [comment]
@heyman333 님
요거 해커톤때 작업해주신 것 맞죠~?!

**Comment by heyman333** [comment]
@Dumbs-app 네네 맞습니다!!
