### ISSUE TITLE
[iOS] 쿠폰레이어 관련 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#36]
### [이슈내용]
![Image](https://github.com/user-attachments/assets/dd7980a4-1019-407f-9c5f-194abe6d01c8)
- 테스트쿠폰1, 테스트쿠폰3이 쿠폰레이어에서 아래 이미지와 같이 제대로 노출되지않고있음
![Image](https://github.com/user-attachments/assets/c9a04c85-5cfa-47e2-b810-e4529149c861)

[개선방향]
- 테스트쿠폰 2,3,5처럼 아래 이미지와 같게 노출되어야 합니다!
![Image](https://github.com/user-attachments/assets/ad645c32-573e-4092-94ab-ad30e6e1a16a)

@somedd 재욱님 
요거 아침에 현준님이 업데이트 하시고 나서부터
재현되고있는 것 같습니다ㅠ
안드로이드는 정상노출되는 것으로 보아 iOS 이슈인듯 한데
시간나실때 확인 부탁드려요!

cc. @txtart

**Comment by Dumbs-app** [comment]
@somedd 님
현재` 테스트쿠폰 1, 3` (기간 상시노출 쿠폰들)은
다운로드 완료 후에 눌렀을때
`쿠폰디테일`(바코드있는화면)이 노출되지 않고 로딩인디케이터만 뜨고 있는데
안드에서는 정상노출 되고 있어서, 이것도 같이 확인 부탁드릴게요!!
https://github.com/user-attachments/assets/519ce99f-2541-445b-83b9-49567760fa36

**Comment by somedd** [comment]
1.0.3에서 수정 cc. @Dumbs-app
