### ISSUE TITLE
[App][And] 홈 리스트 > 운영시간, 입장료, 쿠폰 정보 관련 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#37]
[현재 문제점]
![KakaoTalk_Photo_2024-08-28-23-10-19](https://github.com/user-attachments/assets/2e0a8bb8-df04-45c1-b96b-01c21958c5bf)
### 1. 입장료 정보 미노출 이슈
- 세비지 이외 업장은 입장료정보가 미노출되고있음

### 2. 'CLOSED' 표기
- close-> closed로 표기 변경 필요

### 3. 활성화된 쿠폰 리스트에서 미노출 되고 있음 (상세에선 노출중)

@whtjdhks3837 서완님 확인 부탁드리겠습니다~!

**Comment by whtjdhks3837** [comment]
@Dumbs-app 입장료 정보는 서버에서 내려주는 "feeNote"를 보고있습니다. feeNote가 내려오지 않으면 아무 노출을 해주고있지 않은데 정리가 필요할 것 같아요

{
  "success": true,
  "data": {
    "gender": null,
    "items": [
      {
        "no": 14,
        "storeName": "DUMBS",
        "storeType": "클럽",
        "genre": [
          "테크노"
        ],
        "lat": "0.0000000000",
        "lng": "0.0000000000",
        "locationName": "압구정ㆍ신사",
        "admissionFee": null,
        "feeNote": null,
        "isOpen": false,
        "isLike": false,
        "coupon": {
          "id": 19,
          "name": "테스트쿠폰1",
          "description": "상시노출/제한없음1",
          "startDate": null,
          "endDate": null,
          "quantity": null,
          "remainingQuantity": null,
          "downloadCount": 10,
          "gender": "m,w",
          "isActive": true,
          "order": 0,
          "deletedAt": null,
          "isDownload": false
        },
        "storeImage": "https://cdn.dumbs.app/biz/images/a180ce18bf9a5e70/1725556532420-89f8ca07525b3404.jpeg"
      },
      {
        "no": 19,
        "storeName": "어텐션",
        "storeType": "클럽",
        "genre": [
          "힙합",
          "R&B",
          "K-POP"
        ],
        "lat": "0.0000000000",
        "lng": "0.0000000000",
        "locationName": "기타",
        "admissionFee": {
          "m": 0,
          "w": 0
        },
        "feeNote": "공연 및 파티에는 입장료가 있을 수도 있습니다.",
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/549039b54fe459ef/1726383169564-84d21aa3632a1353.jpeg"
      },
      {
        "no": 15,
        "storeName": "언더그라운드",
        "storeType": "라운지·펍",
        "genre": [
          "힙합",
          "R&B"
        ],
        "lat": "37.5350863296",
        "lng": "126.9923969316",
        "locationName": "이태원",
        "admissionFee": {
          "m": 0,
          "w": 0
        },
        "feeNote": "",
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/62fcb932ae368af8/1725286951179-87177fb469140203.jpeg"
      },
      {
        "no": 13,
        "storeName": "매드홀릭 이태원",
        "storeType": "클럽",
        "genre": [
          "R&B",
          "힙합",
          "팝"
        ],
        "lat": "37.5348640622",
        "lng": "126.9925453968",
        "locationName": "이태원",
        "admissionFee": null,
        "feeNote": null,
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/b8ff559b8559b536/1724506649132-1a54b59bed8fd008.jpeg"
      },
      {
        "no": 18,
        "storeName": "배드에스",
        "storeType": "클럽",
        "genre": [
          "힙합"
        ],
        "lat": "37.5348416487",
        "lng": "126.9928928588",
        "locationName": "이태원",
        "admissionFee": null,
        "feeNote": null,
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": ""
      },
      {
        "no": 11,
        "storeName": "다이브",
        "storeType": "클럽",
        "genre": [
          "힙합",
          "R&B"
        ],
        "lat": "37.5348538239",
        "lng": "126.9930898382",
        "locationName": "이태원",
        "admissionFee": null,
        "feeNote": null,
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": ""
      },
      {
        "no": 12,
        "storeName": "쿠키",
        "storeType": "클럽",
        "genre": [
          "힙합",
          "R&B",
          "팝"
        ],
        "lat": "37.5340421353",
        "lng": "126.9934964287",
        "locationName": "이태원",
        "admissionFee": {
          "m": 0,
          "w": 0
        },
        "feeNote": "",
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/8d2df582cb053b12/1724978781440-50cd59ead3cd1d74.jpeg"
      },
      {
        "no": 16,
        "storeName": "레드룸",
        "storeType": "라운지",
        "genre": [
          "힙합",
          "R&B",
          "팝"
        ],
        "lat": "37.5349516598",
        "lng": "126.9945696184",
        "locationName": "이태원",
        "admissionFee": {
          "m": 0,
          "w": 0
        },
        "feeNote": "",
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/b8ff559b8559b536/1724660560971-a075bcdedd95fa2b.jpeg"
      },
      {
        "no": 8,
        "storeName": "세비지",
        "storeType": "CLUB",
        "genre": [
          "R&B",
          "힙합",
          "팝"
        ],
        "lat": "37.5347275905",
        "lng": "126.9947827942",
        "locationName": "이태원동",
        "admissionFee": {
          "m": 10000,
          "w": 10000
        },
        "feeNote": "12시 이전 무료입장",
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/bfbb1c00d03636a2/1721746708270-2e447e9d3b5196cb.jpeg"
      },
      {
        "no": 17,
        "storeName": "로코컴플렉스",
        "storeType": "라운지",
        "genre": [
          "힙합",
          "R&B",
          "팝"
        ],
        "lat": "37.5273049237",
        "lng": "127.0382351649",
        "locationName": "압구정ㆍ신사",
        "admissionFee": null,
        "feeNote": null,
        "isOpen": false,
        "isLike": false,
        "coupon": null,
        "storeImage": ""
      },
      {
        "no": 9,
        "storeName": "키키",
        "storeType": "CLUB",
        "genre": [
          "R&B",
          "팝",
          "힙합"
        ],
        "lat": "37.5411920459",
        "lng": "127.0700718553",
        "locationName": "화양동",
        "admissionFee": {
          "m": 0,
          "w": 0
        },
        "feeNote": "",
        "isOpen": true,
        "isLike": false,
        "coupon": null,
        "storeImage": "https://cdn.dumbs.app/biz/images/aab17959d0c654df/1720687914726-246d31dd426e121a.jpeg"
      }
    ],
    "total": 11,
    "currentPage": 1,
    "totalPage": 1
  }
}
