### ISSUE TITLE
[어드민] > [가게정보>[가게이름(영어)]  [특수문자이슈]

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/Dumbs_phase2#39]
[테스트 환경]
mac>chrom

[현재 문제점]
<img width="736" alt="스크린샷 2024-09-15 오후 3 31 05" src="https://github.com/user-attachments/assets/019fcaf3-8ba8-40ed-8315-4a819f3c5a06">

가게이름(영어)
입력할때 : ,@,#,! 등 특수문자 입력 불가 이슈

[개선사항]

특수문자 입력 가능하게 수정

**Comment by hateyoon** [comment]
가게이름 >국문입력칸
은 특수문자 입력 가능하고 앱에서도 적용 확인 되었습니다
영어입력칸만 수정하면 될 것 같습니다!

**Comment by heyman333** [comment]
@hateyoon 수정완료!

**Comment by Dumbs-app** [comment]
확인완료! 감사합니당~!

**Comment by Dumbs-app** [comment]
@heyman333 님~!
저번에 반영된거 확인했었는데,
지금 다시 확인해보니 다시 특문 입력 안되네요ㅠㅠ
확인 한번 부탁드릴게용!

**Comment by heyman333** [comment]
<img width="800" alt="스크린샷 2024-09-28 오후 6 44 43" src="https://github.com/user-attachments/assets/adccbc1e-b35d-459d-b0ce-31e9691f14e8">
@Dumbs-app 혹시 어떤 특수 문자 입력이 안되나요?

**Comment by Dumbs-app** [comment]
: 입력시 안됐어용! !도 안됐음 ㅠ
