### ISSUE TITLE
[App][쿠폰] 쿠폰관련 이슈 - 세분화예정

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#40]
[현재 문제점]
### 1. 활성화 되어있는 쿠폰 미노출됨
- 상세페이지에서는 표시되는데, 홈리스트에서 뜨지 않습니다

### 2. 쿠폰 다운로드 오류
재현환경: 비로그인시 -> 상세 진입 후 `COUPON(다운로드화살표아이콘)`버튼 클릭
-> 쿠폰바텀시트 노출됨 -> `쿠폰다운로드` 버튼 클릭
-> 로그인 팝업 노출됨 -> 로그인완료

이슈사항:
로그인완료 후 쿠폰 바텀시트에서 `쿠폰다운로드` 버튼 클릭 
-> '이미 다운로드완료된 쿠폰입니다' 오류 팝업 노출됨
-> 바닥페이지에는 여전히 `COUPON(다운로드화살표아이콘)` 버튼이 노출됨
<img width="132" alt="스크린샷 2024-08-28 오후 10 55 20" src="https://github.com/user-attachments/assets/f7ce077c-aa48-4947-964e-0ba35a87b88c">

개선사항:
쿠폰이 다운로드 완료되었을 경우, `COUPON( 체크아이콘)` 이 노출되어야 함
<img width="98" alt="스크린샷 2024-08-28 오후 10 57 41" src="https://github.com/user-attachments/assets/04fe0277-0857-407f-8863-c632eba08f70">

### 2-1.  쿠폰 다운로드 완료 후
- COUPON(체크아이콘) 클릭 시 쿠폰바코드 화면 노출되어야 함 ([figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=1772-66531&t=8WYEhGrdGEEYdsPI-1))
<img width="348" alt="스크린샷 2024-08-28 오후 10 56 35" src="https://github.com/user-attachments/assets/00cfbb9d-1710-441f-b637-dd72c58fb358">

### 3. 자동으로 쿠폰 만료 처리됨
- 쿠폰을 아직 사용하지 않았는데, 만료처리되는 이슈 (#79 )

### 4. 마이페이지 > 쿠폰 영역
- 쿠폰갯수에 만료된 쿠폰 갯수가 카운트되고있음
-> 사용가능한 쿠폰 갯수만 카운트되어야 함
![IMG_3259](https://github.com/user-attachments/assets/a0db2fae-8921-48bf-8228-fb356072799b)

@somedd 님
쿠폰관련된 이슈 전달드립니다~! 확인 부탁드립니당

**Comment by txtart** [comment]
@Dumbs-app 1번 이슈 정보 쿠폰 이름이나 내용 등등 주시면 감사하겠습니다

**Comment by Dumbs-app** [comment]
@txtart (cc. @somedd )
**1번이슈 테스트**

case 1. 상시노출/제한없음으로 발행한 쿠폰
- 홈에서는 노출되고 상세에서는 노출되지 않고있음
- 안드,ios 동일

case2. 기간제한/수량제한 O 로 발행한 쿠폰
- 상세에서는 노출되고 홈에서는 노출되지 않고있음
- 안드,iois 동일

**Comment by Dumbs-app** [comment]
### 5. 쿠폰명대신 서브문구가 노출되고있음

<img width="242" alt="스크린샷 2024-09-10 오전 12 35 47" src="https://github.com/user-attachments/assets/952a746d-d9fa-4cd8-9850-d0b047ab6921">

@txtart 요 부분 추가로 확인 부탁드릴게요ㅠㅠ 
안드랑 ios에서 동일하게 나타나는 것으로 보아 서버이슈가 아닐까 합니당.

**Comment by txtart** [comment]
@somedd, @whtjdhks3837 님 

5번 이슈 확인 좀 해주실래요?

**Comment by Dumbs-app** [comment]
@whtjdhks3837 @somedd 5번내용 리마인드 드립니다!

**Comment by Dumbs-app** [comment]
@whtjdhks3837 님
5번 이슈 (홈 리스트에서 타이틀대신 서브문구노출되는 문제) 확인부탁드릴게용!!

**Comment by Dumbs-app** [comment]
반영확인하여 클로즈합니다!
