### ISSUE TITLE
[어드민] 쿠폰관련이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#41]
[테스트 환경]
https://admin.dumbs.app/info/coupon

[현재 문제점]
@heyman333 @3d3nch01 
쿠폰관련 이슈 확인 부탁드립니다!

### 1. 잔여쿠폰0개 시
<img width="705" alt="스크린샷 2024-08-28 오후 10 32 22" src="https://github.com/user-attachments/assets/03de6597-8fda-4d51-80fa-2ab623e383e5">

- 잔여 쿠폰이 없는 경우 자동으로 비활성처리 필요
- 앱에는 안뜨는데 어드민엔 활성화돼있어서 헷갈림

### 2. 쿠폰 수량 
<img width="719" alt="스크린샷 2024-08-28 오후 10 34 33" src="https://github.com/user-attachments/assets/af80600f-4091-4246-a0b6-7318d8a92c63">

- 수량제한 없음 클릭시 0개로 셋팅됨 (쿠폰생성은 됐는데 아예 사용이 안되기땜에 좀 크리티컬함 ㅠ)
- max값을 999개 등으로 설정해주는 등 대응 필요 @3d3nch01 님 확인해주세요!

### 3. 유의사항 영역
<img width="730" alt="스크린샷 2024-08-28 오후 10 30 49" src="https://github.com/user-attachments/assets/e8863748-f9a9-443e-b42d-ae4d05c55ce7">

- 구두점이 박스 밖으로 나가있는데 수정부탁드립니다~!

**Comment by heyman333** [comment]
@Dumbs-app @txtart 남은 쿠폰이 없을 경우 비활성화는 서버에서 처리 해주시면 될거같아요! 수량이 0일 경우 테이블에서 제한없음으로 출력하도록 수정했습니다!

**Comment by txtart** [comment]
좀 더 고민을 해봤을때 활성화 비활성화와 만료 여부를 따로 관리하는게 좋아보이네요

**Comment by txtart** [comment]
@Dumbs-app 0개로 셋팅된다는게 어디뷰예요? 이거 는 개발자들이랑 얘기해서 다른 방법으로 표기하거나 표기가 안되게 하는게 좋을듯한데 가이드잡아주시면 좋을거같아요

**Comment by txtart** [comment]
@heyman333 수량제한없음의 경우 0 말고 null로 처리해주세요~DB수정해두었어요

**Comment by Dumbs-app** [comment]
> @Dumbs-app 0개로 셋팅된다는게 어디뷰예요? 이거 는 개발자들이랑 얘기해서 다른 방법으로 표기하거나 표기가 안되게 하는게 좋을듯한데 가이드잡아주시면 좋을거같아요 

![image](https://github.com/user-attachments/assets/51205a0e-43bf-4788-9888-5934b49fbd5b)
@txtart  여기 뷰 말한거였는데 반영되어있네유
전에는 생성하자마자 0/0 으로 표시되고 
0개이기때문에 앱에 나타나지지도않았음!

근데 제한없음까진 좋은데 그래서 사용된 수량이 몇갠지는 알수가 없어여ㅜ

그리고 수량제한없음 시
쿠폰 비활성화나 삭제는 언제든 가능하다는 문구가
버튼 근처에 나와도 좋을 듯 하네예
Cc. @3d3nch01

**Comment by Dumbs-app** [comment]
2,3번은 반영완료
1번은 #61 로 이슈 분기해서 해당 이슈는 클로즈처리 해둘게요~!
