### ISSUE TITLE
[어드민] 1차어드민 - 로그인뷰 변경

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#43]
@3d3nch01 님
1차어드민 로그인 뷰 가이드 전달부탁드립니다~!

**Comment by 3d3nch01** [comment]
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3377-145023&node-type=frame&t=sz4GLpbCKQoWVyaF-11

로그인 뷰는 2차 어드민과 거의 동일하고, 회원가입 버튼만 제외했습니다!

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/29d27d08-e5c4-4ae8-bcf6-121672a804ca">

**Comment by Dumbs-app** [comment]
@heyman333 님
이어서 작업 부탁드리겠습니다~!

**Comment by Dumbs-app** [comment]
작업된 것으로 확인
https://dumbs-backoffice.netlify.app/
