### ISSUE TITLE
[어드민] [우리가게입점하기] [대표계정생성] (비밀번호 가이드라인)

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/Dumbs_phase2#44]
[테스트 환경]
Mac> chrom

[현재 문제점]

<img width="418" alt="스크린샷 2024-09-15 오후 3 54 48" src="https://github.com/user-attachments/assets/f3863cf6-f9f3-4647-8b40-b6ef3c3c47a2">

8~16자의 영문 대/소문자, 숫자,
특수문자(, . 제외)를 사용해 주세요.
이 가이드라인이 비밀번호 입력할 때 생각보다 업장측에서 혼선이 한번씩은 꼭 있음

[개선사항]
영문 소문자,숫자, 특수문자 를 넣어야 하는다는 명확한 가이드 라인이 필요함

**Comment by Dumbs-app** [comment]
@3d3nch01 

- asis: 8~16자의 영문대/소문자, 숫자, 특수문자(, .제외)를 사용해주세요
- tobe: 8~16자의 영문, 숫자, 특수문자(, .제외)를 모두 포함해서 작성해 주세요.

요렇게 제안드려 봅니다~!

**Comment by 3d3nch01** [comment]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/61bc0747-d97f-4ad5-8eb2-22dd46af540d">

디자인 수정완료하였고
줄바꿈만 1줄 들어갑니다!

여기서 확인하실 수 있습니다.

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=1502-57943&node-type=frame&t=sz4GLpbCKQoWVyaF-11

**Comment by Dumbs-app** [comment]
@heyman333 
영수님 문구수정 반영 부탁드리겠습니당~!!

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 수정완료!

**Comment by Dumbs-app** [comment]
확인완료~!
