### ISSUE TITLE
[iOS] 업체정보 > 공연/파티 서브문구 말줄임처리

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#46]
[현재]
![Image](https://github.com/user-attachments/assets/4d6d6715-59af-4608-b06b-c0614587f1d6)

[개선방향]
![Image](https://github.com/user-attachments/assets/5a15ffa2-6fae-4135-962a-141b6e67d1b3)
[Figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3315-9109&t=eHBjt4gwQmnDNY4P-1)

@somedd 님
공연/파티 서브문구 최대 3줄 노출+말줄임처리 부탁드립니다~!

**Comment by somedd** [comment]
1.0.3에서 수정 cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
@somedd 님
반영 확인했습니다 :)
그런데 혹시 본문텍스트/이미지 클릭시에도 
해당 공연상세로 이동하도록 클릭영역 추가 부탁드릴 수 있을까요?!

**Comment by somedd** [comment]
> @somedd 님 반영 확인했습니다 :) 그런데 혹시 본문텍스트/이미지 클릭시에도 해당 공연상세로 이동하도록 클릭영역 추가 부탁드릴 수 있을까요?!

1.0.4에 반영하였습니다 :) cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
확인완료! 감사합니다~!
