### ISSUE TITLE
[App][And] 업체정보 > 공연/파티 서브문구 말줄임처리

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#47]
[현재]
![Image](https://github.com/user-attachments/assets/4d6d6715-59af-4608-b06b-c0614587f1d6)

[개선방향]
![Image](https://github.com/user-attachments/assets/5a15ffa2-6fae-4135-962a-141b6e67d1b3)
[Figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3315-9109&t=eHBjt4gwQmnDNY4P-1)

@whtjdhks3837  님
공연/파티 서브문구 최대 3줄 노출+말줄임처리 부탁드립니다~!

**Comment by Dumbs-app** [comment]
@whtjdhks3837 님
요거 반영 확인했는데요~~
혹시 본문텍스트/이미지 클릭시에도 
해당 공연상세로 이동하도록 클릭영역 추가 부탁드릴 수 있을까요?!

**Comment by Dumbs-app** [comment]
> [@whtjdhks3837](https://github.com/whtjdhks3837) 님 요거 반영 확인했는데요~~ 혹시 본문텍스트/이미지 클릭시에도 해당 공연상세로 이동하도록 클릭영역 추가 부탁드릴 수 있을까요?!

![Image](https://github.com/user-attachments/assets/d99d1c5f-e0aa-4e54-a5ee-62ada370e70d)
@whtjdhks3837 서완님~ 표시한 영역 클릭시에도
자세히보기로 넘어가는걸로 요청드린 거였는데요!
반영안되어보여서 한번 더 확인 부탁드리겠습니다!

**Comment by whtjdhks3837** [comment]
@Dumbs-app 반영되어있는데 아마 이전빌드로 보신것 같아요 최신 빌드 전달드리면 확인 부탁드립니다

**Comment by Dumbs-app** [comment]
반영확인하여 클로즈합니다!
