### ISSUE TITLE
[iOS] 비로그인 상태에서 쿠폰 클릭 > 로그인완료 후 쿠폰 다운로드 시 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#48]
[이슈사항]
비로그인 상태에서
쿠폰 클릭한 뒤
로그인하러가기 -> 로그인완료

이후 쿠폰 바텀시트에서 `쿠폰다운로드` 버튼 재클릭 
-> '이미 다운로드완료된 쿠폰입니다' 오류 팝업 노출됨
-> 바닥페이지에는 여전히 `COUPON(다운로드화살표아이콘)` 버튼이 노출됨
<img width="132" alt="스크린샷 2024-08-28 오후 10 55 20" src="https://github.com/user-attachments/assets/f7ce077c-aa48-4947-964e-0ba35a87b88c">
-> 페이지 벗어났다가 다시 들어오면 정상 UI(다운로드완료된 아이콘) 노출됨

[개선사항]
비로그인 상태에서 쿠폰 다운로드 시도한 뒤
로그인완료 하고 다시 다운로드 시도했을 경우
'이미 다운로드 완료된 쿠폰입니다' 오류팝업 노출되지 않고
다운로드 완료되어야함

#40 이슈의 2번 내용 세분화함
@somedd 님 확인 부탁드리겠습니다~!

**Comment by somedd** [comment]
1.0.4버전에서 수정완료
@Dumbs-app 앱 프리징 이슈는 새로 등록해주세요!
