### ISSUE TITLE
[App][로그인] 로그인 실패시 오류메시지

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#49]
[테스트환경]
1.0.3(2)

[이슈상황]
아이디/비밀번호 미일치시 오류메시지가 제대로 노출되지 않고 있음
https://github.com/user-attachments/assets/7dda5ff2-0ad5-4ba3-8f30-7320d57b91f1
https://github.com/user-attachments/assets/97dff932-08a6-434c-9404-eca64d1f86d9

[참고사항]
유저정보가 없는 경우에는 오류메시지가 정상 노출되고 있음
![Image](https://github.com/user-attachments/assets/b44c994e-663a-41d8-9326-b0d6d3f03675)

[개선사항]
정보 불일치시 오류메시지 노출 필요 ([figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3315-10777&t=uvlAuwp5hKOS43mD-1))
![Image](https://github.com/user-attachments/assets/e19b7709-9ba0-405f-9610-ca6e9ea3641b)

**Comment by somedd** [comment]
@Dumbs-app 이 문구는 서버에서 내려오는 메세지여서 서버쪽에서 수정해주셔야할 것 같아요! cc. @txtart

**Comment by Dumbs-app** [comment]
@txtart 님 확인 부탁드려요!

**Comment by somedd** [comment]
@Dumbs-app 어싸이니랑,  iOS 레이블 빼두었어용~

**Comment by Dumbs-app** [comment]
@txtart 
![Image](https://github.com/user-attachments/assets/a44803fa-d3dd-434b-be55-33554abdfbe7)

오류메시지 서브문구 이렇게 수정 부탁드립니다!

**Comment by txtart** [comment]
오른쪽 팝업 처럼 나오면 이메일이 존재하는지 체크가 쉬워지고 이메일이 존재하기 때문에 비번만 바꾸면서 해킹 시도 계속 들어와서
1번 알럿만 있는게 좋을듯합니다.

**Comment by Dumbs-app** [comment]
@txtart 1번 알럿 띄우는 형태로 수정 진행해주세요~!

**Comment by Dumbs-app** [comment]
@txtart 아직재현됩니다! 1번 가이드로 변경 부탁드려요

**Comment by txtart** [comment]
@somedd 님 @whtjdhks3837 님 클라에서 에러 메시지 보시고 분기 처리 좀 해주세요

**Comment by somedd** [comment]
iOS - 1.1.0(6) 에서 수정. cc @Dumbs-app

**Comment by Dumbs-app** [comment]
확인완료했습니다~! 감사합니다!
