### ISSUE TITLE
[iOS] 회원가입 관련 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#50]
### [테스트환경]
1.0.3

### [이슈내용&개선방향]
**1. 이메일 형식 잘못 입력하거나 이름에 영어 입력 시 등 오류상황에서
키보드의 `next`를 누르면 오류문구 노출 없이 다음단계로 넘어가짐**
- 키보드 next 눌렀을 때 바로 다음 플로우로 가지 않고 오류 검증 필요

**2. 비밀번호 > 영문+숫자가 모두 조합되지 않았는데도 넘어가짐**
- 영문+숫자 모두 포함 검증 필요
- 영문+숫자 모두 미포함시 에러문구 노출필요 ([가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3315-11422&t=uvlAuwp5hKOS43mD-1))

**3. 주민번호 뒷자리 입력시 긴 숫자도 입력됨**
- 1자리만 입력되게 변경 가능할까요?

@somedd 님 확인 부탁드립니다!

**Comment by somedd** [comment]
1.0.4 버전에서 반영 cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
확인완료! 감사합니당~!
