### ISSUE TITLE
[App][And][회원가입] 비밀번호에 특수문자 입력 가능하도록 변경 필요

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#51]
**[현재이슈]**
비밀번호에서 특수문자 입력이 불가함

**[개선방향]**
특수문자 입력 가능하게 변경 필요

@whtjdhks3837 님 확인 부탁드립니다~!

**Comment by Dumbs-app** [comment]
@whtjdhks3837 님~!
지금도 `! . : @` 등 테스트 했을때 
'올바른 형식으로 입력해주세요' 텍스트가 노출됩니다!
한번 더 확인 부탁드려용 ㅠ.ㅠ

**Comment by whtjdhks3837** [comment]
@Dumbs-app 영문 + 숫자가 들어간 상태에 특수문자를 넣어야하는데 영문, 숫자, 특수문자 상관없이 8-12자리면 될까요?

**Comment by Dumbs-app** [comment]
@whtjdhks3837 
네~~! 맞습니당
최대12자는 아니구 <최소 8자 이상> 조건만 적용되면 됩니다!

**Comment by Dumbs-app** [comment]
테스트빌드에서 확인 완료하여 이슈 닫겠습니다! 감사합니다~~
