### ISSUE TITLE
[어드민] 2차어드민 - 쿠폰리스트 > 유효기간정보 추가 필요

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#53]
<img width="796" alt="image" src="https://github.com/user-attachments/assets/6017e604-6643-4223-9369-227799aa434d">
@heyman333
영수님 쿠폰 생성 후 완료 테이블 리스트에서 '쿠폰 유효 기간' <- 다운로드 받고 나서 사용할 수 있는 기간
정보가 추가되어 전달드립니다!

[Figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3408-121122&node-type=frame&t=I3VPsKn5DTwcpLXP-11)

@3d3nch01 님
2차어드민에서
쿠폰 리스트에도 '유효기간' 정보 추가가 필요할 것 같아요~! 
디자인 부탁드립니다
![Image](https://github.com/user-attachments/assets/c0351b33-ac07-48d2-994f-b624edff80ac)

**Comment by 3d3nch01** [comment]
@Dumbs-app 확인했습니당 우선순위 혹시 높을까요? 관리자계정 <> 업체 정보 분리부터 마무리하고 진행하려 합니다

**Comment by Dumbs-app** [comment]
넹넹 P0 건들부터 부탁드려요~!

**Comment by Dumbs-app** [comment]
@3d3nch01 
추후에 #61  이슈 내용도 같이 참고해서 반영해주시면 좋을 것 같습니다용~!
(잔여 쿠폰 수량 표기)

**Comment by heyman333** [comment]
완료!

**Comment by Dumbs-app** [comment]
테스트서버 확인완료했습니다~!

**Comment by Dumbs-app** [comment]
@heyman333 
영수님~~ 리얼에도 반영 완료 확인했는데요!
마이너하긴 한데
'노출기간' 레이블을 '쿠폰 노출기간' 으로 변경가능할까요..?!
cc. @3d3nch01 

![Image](https://github.com/user-attachments/assets/21d683da-990f-401e-8565-635e55440f9b)

**Comment by 3d3nch01** [comment]
@Dumbs-app 확인했습니당 디자인 변경해뒀구
https://docs.google.com/spreadsheets/d/1sSy9KZEHWsQwi0xon-Jl593y_le2OPzLkc2VbhYl138/edit?gid=892574592#gid=892574592
시트에도 제가 올려 둘게여

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 수정완료!
