### ISSUE TITLE
[iOS] 홈 > 정렬기준 텍스트 '거리순'으로 변경

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#54]
### [테스트환경]
1.0.4

### [이슈내용]
홈에서 정렬기준이 '추천순' 으로 노출되고 있음
![Image](https://github.com/user-attachments/assets/77b4632f-1e5c-4fed-94b8-79e9281b9ab4)

### [개선방향]
'거리순' 으로 변경 부탁드립니다!

@somedd

**Comment by somedd** [comment]
수정완료! 1.0.5에서 반영 예정입니다~! cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
확인완료~! 감사합니다~!
