### ISSUE TITLE
[랜딩] 이용약관, 개인정보처리방침 링크 연결

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#55]
@heyman333 님

유저이용약관 
http://butternut-wealth-2ff.notion.site

개인정보처리방침
https://butternut-wealth-2ff.notion.site/_240929-10f6d1c90d6080839f3cde501a9e81c0?pvs=4

**Comment by heyman333** [comment]
@Dumbs-app 완료!

**Comment by Dumbs-app** [comment]
확인완! 감사합니다~!
