### ISSUE TITLE
[어드민] 2차어드민 - 쿠폰 생성 UI 및 텍스트 변경

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#57]
### AS-IS
<img width="725" alt="image" src="https://github.com/user-attachments/assets/5755e72d-0c38-4107-8e95-e14d42dc973b">

### TO-BE
<img width="907" alt="image" src="https://github.com/user-attachments/assets/30dea43f-a7be-45c7-a4f3-b0398c35a8a5">

### 변경 사항

1. 인풋 순서 변경

2. '수량 제한 없음' -> '장수 제한 없음' 으로 워딩 변경

3. 쿠폰 유효 사용 기간 텍스트 입력 -> 라디오버튼으로 변경

4. 경고 안내 문구 디자인 변경 (컬러)

**Comment by 3d3nch01** [comment]
@heyman333 새 쿠폰 생성 시 바뀐 점 정리해서 전달드립니다!

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 다시 확인 부탁드립니다~

**Comment by Dumbs-app** [comment]
확인완료되어 클로즈합니다~!
