### ISSUE TITLE
[어드민] 쿠폰 발행후 잔여수량 표기 필요

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#61]
> @Dumbs-app 0개로 셋팅된다는게 어디뷰예요? 이거 는 개발자들이랑 얘기해서 다른 방법으로 표기하거나 표기가 안되게 하는게 좋을듯한데 가이드잡아주시면 좋을거같아요 
> 
> ![image](https://github.com/user-attachments/assets/51205a0e-43bf-4788-9888-5934b49fbd5b)
> @txtart  여기 뷰 말한거였는데 반영되어있네유
> 전에는 생성하자마자 0/0 으로 표시되고 
> 0개이기때문에 앱에 나타나지지도않았음!
> 
> 근데 제한없음까진 좋은데 그래서 사용된 수량이 몇갠지는 알수가 없어여ㅜ
> 
> 그리고 수량제한없음 시
> 쿠폰 비활성화나 삭제는 언제든 가능하다는 문구가
> 버튼 근처에 나와도 좋을 듯 하네예
> Cc. @3d3nch01  

 _Originally posted by @Dumbs-app in [#41](https://github.com/Dumbs-app/Dumbs_phase2/issues/41#issuecomment-2351417368)_

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 배포 완료!

**Comment by 3d3nch01** [comment]
<img width="491" alt="image" src="https://github.com/user-attachments/assets/9f637cee-7d35-4b55-8420-583d743c9cb5">
@heyman333 요 부분 전달드립니다!

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3408-121122&node-type=frame&t=I3VPsKn5DTwcpLXP-11

**Comment by Dumbs-app** [comment]
확이인
