### ISSUE TITLE
[어드민] 쿠폰 5개 최대 활성화 상태에서 새 쿠폰 생성 시 알럿 추가

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#63]
### AS-IS
1. 새 쿠폰 생성시 앱 내 노출 토글 '비활성화'
2. 5개 이상 시 경고 문구 1회 노출, 새 쿠폰 생성 가능

### TO-BE
1. 새 쿠폰 생성 시 앱 내 노출 토글 '활성화'
2. 5개 이상 생성 시, 경고 알럿 1회 노출, 알럿 닫고 토글 1개 이상 비활성화하기 전까지 새 쿠폰 생성 불가

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 수정완료!

**Comment by Dumbs-app** [comment]
확인했슴다!!!!!

**Comment by 3d3nch01** [comment]
아직 QA 중이라서 다시 오픈합니다아!!! cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
![Image](https://github.com/user-attachments/assets/051a6a69-9523-4546-ad6b-84a600dbfd8f)

옹 저는 요렇게 잘 나오긴 하네여! 참고링 @3d3nch01

**Comment by 3d3nch01** [comment]
아 네네 여기 요렇게 문구를 추가하려고요! 참고링 @Dumbs-app 
<img width="798" alt="image" src="https://github.com/user-attachments/assets/fafe198c-38b5-48ec-a6a5-38ff9157416f">

**Comment by Dumbs-app** [comment]
요거 근데 텍스트 @heyman333 영수님이 바로 수정해주실 수 있으실 것 같은데!
이슈있으실까욤?! @3d3nch01 님

**Comment by 3d3nch01** [comment]
@Dumbs-app  이슈 없습니당!
영수님께서 바로 확인해주시면 될 것 같아요.
https://docs.google.com/spreadsheets/d/1sSy9KZEHWsQwi0xon-Jl593y_le2OPzLkc2VbhYl138/edit?gid=892574592#gid=892574592
QA시트 8번에 정리해두었습니다 @heyman333

**Comment by heyman333** [comment]
@3d3nch01 수정완료!

**Comment by 3d3nch01** [comment]
@heyman333 진짜 마이너하지만 '한개' → '한 개'로 부탁드립니다! 확인 완료~~!!!

**Comment by heyman333** [comment]
@3d3nch01 수정완료!

**Comment by Dumbs-app** [comment]
확인완료요!!! 감사합니다~~!!
