### ISSUE TITLE
[Server][어드민][QA] 2차 어드민 로그인 후 시간 지나면 가게 정보 날아가는 이슈

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#65]
<img width="752" alt="image" src="https://github.com/user-attachments/assets/51215bf5-b8c9-4f81-b100-2615bcfb6b02">

로그인 후 2일정도 창을 그대로 놔뒀다가
새로고침했더니 
기존에 입력했던 가게 정보가 날아갔습니다!

<img width="339" alt="image" src="https://github.com/user-attachments/assets/d6a7318d-2d2d-40b4-acbb-5b9d5a6988d9">

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 요거 현준이랑 얘기 해봐야될거같은데 일단은 세션 날라가면 로그인창으로 보내도록할게영 ㅜㅜ

**Comment by heyman333** [comment]
@Dumbs-app @3d3nch01 수정완료!

**Comment by Dumbs-app** [comment]
로그인창으로 이동 확인은 했습니다!
근데 꽤 빨리 로그인이 풀리는 것 같아서
최대한 길게 or 영구적으로 로그인되어있게 확인 부탁드려요 ! @txtart

**Comment by 3d3nch01** [comment]
@txtart @Dumbs-app 께서 댓글 달아주신 이슈 
https://github.com/Dumbs-app/Dumbs_phase2/issues/72
로 분리했습니다! 이 이슈는 완료처리하겠습니다.
