### ISSUE TITLE
[어드민] [APP] 지역 기준 정리 요청

### ISSUE THREAD

**Issue by hateyoon** [Dumbs-app/Dumbs_phase2#70]
[테스트환경]
And-app

![KakaoTalk_Photo_2024-10-02-18-41-28](https://github.com/user-attachments/assets/637c2fed-1e18-4a9c-981f-1aeda9a74456)

강남베뉴 입점 건 때문에 기존의
(압구정·신사) 에서   

(압구정로데오) ,  (강남·신사)   
으로 추가 및 변경 요청드립니다.

**Comment by txtart** [comment]
@Dumbs-app 님 @3d3nch01 님

저희 정보가 많아 질 경우 이렇게 지역을 다시 재 분류하게 되면 대응이 너무 오래걸려서 가급적이면 지역은 건드리지 않게 초기에 설계 좀 잘부탁드려요 차라리 지역을 뭉치는거 없이 전부다 나누는 것도 방법이고요

**Comment by Dumbs-app** [comment]
@txtart 
압구정로데오
강남·신사

요렇게 가면 추후에도 이슈 없을 것 같아요~!

**Comment by Dumbs-app** [comment]
> [@txtart](https://github.com/txtart) 압구정로데오 강남·신사
> 
> 요렇게 가면 추후에도 이슈 없을 것 같아요~!

@txtart 확인 부탁드립니다
