### ISSUE TITLE
[Server][App][쿠폰] 쿠폰 다운로드 시간 서버 현재시간과 상이하게 노출

### ISSUE THREAD

**Issue by whtjdhks3837** [Dumbs-app/Dumbs_phase2#71]
[테스트 환경]
Android

[현재 문제점]
쿠폰 다운로드 시간 서버 현재시간과 상이하게 노출

[개선사항]
쿠폰 다운로드 시간이 서버 시간과 같게 노출

[기대화면]

**Comment by txtart** [comment]
@whtjdhks3837 님 혹시 리얼인지 dev인지 확인 부탁드려도 될까요? 
저는 아래 처럼 dev에서는 우선 잘나오네요 
<img width="209" alt="image" src="https://github.com/user-attachments/assets/e7b2eb72-c2bf-4a44-b345-af3dd8c2e0cf">

**Comment by txtart** [comment]
리얼에서도 테스트해봤는데 재현불가합니다.
