### ISSUE TITLE
[Server][어드민] 2차 어드민 로그인 유지 시간 조정

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#72]
로그인창으로 이동 확인은 했습니다!
근데 꽤 빨리 로그인이 풀리는 것 같아서
최대한 길게 or 영구적으로 로그인되어있게 확인 부탁드려요 ! @txtart

_Originally posted by @Dumbs-app in https://github.com/Dumbs-app/Dumbs_phase2/issues/65#issuecomment-2396219793_

**Comment by 3d3nch01** [comment]
@heyman333 영수님 이 건 @txtart 에게 내용 전달 받았는데요! cc. @Dumbs-app 
리프레시 토큰을 무한정 연장하고 싶은데 이 건 봐주실 수 있을까요?

- 7일 동안 미로그인시 로그아웃 처리
- 7일 내 재로그인/(로그인 유지 선택 시 재접속) 시 **이후 7일간 로그인 유지**

**Comment by txtart** [comment]
@3d3nch01 님
현재 말씀 주신 기간은 14일로 설정되어 있어서 만약 그 전에 로그인이 풀린다면 @heyman333 님 쪽 이슈일 거 같아서 할당 다시 변경할게요

**Comment by Dumbs-app** [comment]
예전보단 길어진 것 같아서 일단 클로즈합니다..!! cc. @3d3nch01
