### ISSUE TITLE
[Server][App][쿠폰] 쿠폰QA

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#74]
@txtart 
쿠폰QA중 발견된 잔여이슈 여기서 처리하고자합니다
https://docs.google.com/spreadsheets/d/1qW0Ufnwkj3xyPEeP4w-KlQy6qo_7c43ANDw999s67TQ/edit?gid=947859629#gid=947859629

![Image](https://github.com/user-attachments/assets/24323f5f-d00a-4a6c-ba14-e92ade392e7d)

**Comment by txtart** [comment]
@Dumbs-app 님 확인 후 close 처리 부탁해요

**Comment by Dumbs-app** [comment]
@somedd 님
40번 이슈 현재 ios 상세페이지에서 재현되고있어서 확인 부탁드리겠습니다!
- 직원사용 완료된 쿠폰인데 클릭시 쿠폰바코드 재노출됨
- 직원사용 완료시 바로 해당쿠폰 미노출되거나
or 페이지 리프레시 없이 미노출 처리가 어려울 경우 클릭시 '이미 사용한 쿠폰입니다' 얼럿([가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3826-56632&t=4Xtm8Mxh3sTcTZIO-1)) 노출되어야 할 것 같습니다.
- 홈에서는 직원사용 완료 쿠폰 미노출 적용 잘 되어있습니다.

**Comment by Dumbs-app** [comment]
@somedd 님


> [@somedd](https://github.com/somedd) 님 40번 이슈 현재 ios 상세페이지에서 재현되고있어서 확인 부탁드리겠습니다!
> 
> * 직원사용 완료된 쿠폰인데 클릭시 쿠폰바코드 재노출됨
> * 직원사용 완료시 바로 해당쿠폰 미노출되거나
>   or 페이지 리프레시 없이 미노출 처리가 어려울 경우 클릭시 '이미 사용한 쿠폰입니다' 얼럿([가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3826-56632&t=4Xtm8Mxh3sTcTZIO-1)) 노출되어야 할 것 같습니다.
> * 홈에서는 직원사용 완료 쿠폰 미노출 적용 잘 되어있습니다.

1.1.0에서 아직 재현되고있네요..!
요 이슈는 '쿠폰 사용이 완료되었습니다' 토스트얼럿 띄운 뒤에 페이지 리프레시를 해야 해결되지 않을까 싶네요..!!
쿠폰 다운로드에 관련된 이슈는 요게 마지막일 것 같은데,
확인 부탁드리겠습니다!!!

**Comment by somedd** [comment]
@Dumbs-app 쿠폰 사용 완료 후, 리프레시하고 있는데요! 서버에서 처리해주시면 될 것 같습니다 :)

**Comment by Dumbs-app** [comment]
> @Dumbs-app 쿠폰 사용 완료 후, 리프레시하고 있는데요! 서버에서 처리해주시면 될 것 같습니다 :) 

@txtart 님 확인 부탁드려요!!

**Comment by txtart** [comment]
@somedd 님
쿠폰 사용 완료 후 리프레시 제대로 되는지 한번 더 체크해주셔야 될 거 같아요 ! and에서는 이슈 없는데  ios에서만 발생하고 있습니다.

**Comment by somedd** [comment]
1.1.0(6)에서 수정완료! cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
확인완료했습니다! 감사합니다~
