### ISSUE TITLE
[App] 쿠폰 직원 확인 시 버튼 3초간 Long press 기능 추가

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#75]
### 프로토타이핑 링크
[Protopie](https://cloud.protopie.io/p/272404fe84d2c8bf6bec0522)
임의로 만든 거라 2초짜리긴 합니다!

롱프레스 시
- 누르는 동안 btn 내 bar가 width 0 to 100%로 올라갑니다
- 직원확인 옆 (3s) 숫자가 롱프레스 시간에 따라 줄어듭니다.

롱프레스 3초간 누르는 경우
- 쿠폰 확인 모달로 넘어갑니다.

롱프레스 3초 이전에 떼는 경우
- bar가 0.3초간 width 0%로 줄어듭니다.
- 직원확인 옆 (ns) 숫자가 duration 없이 즉시 3s로 원복됩니다.

### Figma

Figma
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3315-11880&node-type=frame&t=xrek743HF4PC1OVY-11

### Task

<img width="730" alt="image" src="https://github.com/user-attachments/assets/ca9955c5-bcfe-419c-adaa-086d7164ef98">

1. 직원확인 옆 (3s) 문구 추가
2. 직원확인 쿠폰 모달 하단 문구 변경
3. 롱프레스 시 텍스트 변경 & bar(#074D31 30%) 노출

**Comment by 3d3nch01** [comment]
@whtjdhks3837 @somedd
서완님, 재욱님! 저희 10/7 월 회의때 논의했던
쿠폰 직원확인 오터치를 줄이기 위한 솔루션으로

'버튼을 3s 롱프레스해야 쿠폰확인이 되도록' 디자인을 변경했습니당. 

https://docs.google.com/spreadsheets/d/1dCNkQ2stPv3dJEC3aHwPOvDJK1XbdvVtgIfvtd1lQCM/edit?gid=1556580434#gid=1556580434&range=37:37

일정표에도 추가해두었으니 일정 체크 후 작업 부탁드립니다~!
참고) 14일 월욜에 오프라인 미팅이라, 이 날 바로 QA까지 완료하겠습니당

**Comment by 3d3nch01** [comment]
cc. @Dumbs-app

**Comment by Dumbs-app** [comment]
반영확인하여 이슈 클로즈합니다! 
빠른 반영 감사합니다!!!
