### ISSUE TITLE
[App][IOS] 쿠폰 유효기간 텍스트 분기처리

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#77]
### [이슈내용&개선사항]

**AS-IS**
- 쿠폰 다운로드 모달(다운받기 전) 화면에서도 'nnnn.nn.nn.까지' 로 표기되어 혼선이 있었음

**TO-BE**
- 쿠폰 다운로드 모달 화면에서는 `다운로드 후 n일 이내 사용 가능` 로 유효기간 표기
- 직원확인(바코드) 화면에서는  `nnnn.nn.nn.까지` 로 유효기간 표기

<img width="666" alt="스크린샷 2024-10-10 오후 4 55 19" src="https://github.com/user-attachments/assets/8f5ee503-4e38-471d-8e61-f6aaa108c7c0">

**Comment by somedd** [comment]
1.1.0에 반영예정입니다~! cc. @Dumbs-app @3d3nch01

**Comment by Dumbs-app** [comment]
@somedd 재욱님~!
직원바코드 화면에서는 반영 확인했는데요!
하단 쿠폰탭 리스트에도 반영 필요할 것 같습니다 (미리 같이 말씀을 못드려 죄송합니다ㅜ)
-> 아래 유효기간에도 `{다운로드받은날+7일뒤 날짜} 까지`로 노출 필요합니다. (현재는 다운로드 받은 날짜가 표기되고 있는 것 같아요!)

![Image](https://github.com/user-attachments/assets/176556ea-ffec-4ddd-8243-bb27e95a1fbf)

**Comment by somedd** [comment]
@Dumbs-app  1.1.0(4) 에서 반영됩니다~!
