### ISSUE TITLE
email 정보가 없는 계정이 존재함

### ISSUE THREAD

**Issue by txtart** [Dumbs-app/Dumbs_phase2#78]
@heyman333 님
디비에 email 정보가 존재하지 않는 계정이 있어서 확인 부탁드릴게요 
<img width="310" alt="image" src="https://github.com/user-attachments/assets/97fd11dc-78c9-4cf0-9b84-76f8d1aa2345">

**Comment by txtart** [comment]
서버쪽에서 "" 이나 undefined일때 에러 response 되도록 해놨어요

**Comment by Dumbs-app** [comment]
@txtart 처리완료한것으로 보고 클로즈해둘게용
