### ISSUE TITLE
[App][iOS][Server][QA] 로그아웃 후 에러 메시지 팝업 

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs_phase2#79]
![IMG_9412](https://github.com/user-attachments/assets/99b79bd1-b914-4b60-a5f8-515877112208)

로그아웃 후 에러 메시지 팝업 뜨고, 가게명 노출되지 않습니다~!
테스트플라이트 최신 1.1.0(2) 입니당

**Comment by somedd** [comment]
@3d3nch01 서버이슈입니다~!!

**Comment by 3d3nch01** [comment]
반영해주셔서 확인 완료했습니다! 완료처리합니다

**Comment by Dumbs-app** [comment]
감사합니다! 고생많으셨습니다~!
