### ISSUE TITLE
[App][IOS] 디자인QA

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#81]
@somedd 님
디자인이슈사항 전달드립니다!
대부분 간격 수정 안이라서 아주 크리티컬하진 않으니
쿠폰관련 이슈 수정후에 봐주시면 감사하겠습니다 :)

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4026-22388&t=rKiE3PDveiyMLKYo-1

![Image](https://github.com/user-attachments/assets/b724ff8d-c858-4faa-8154-8f9841de290e)

**Comment by somedd** [comment]
@Dumbs-app  1.1.0(5) 쿠폰 레이어, 상세페이지 부분 수정 완료하였고, 쿠폰탭은 레이어가 기존 UI랑 좀 애매해서 월요일에 논의해보면 좋을 것 같습니다!

**Comment by Dumbs-app** [comment]
카톡으로 전달드린 내용 코멘트에도 남겨둡니다!
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=4085-12076&t=eX8yuP0tBwPs1yFx-1

**Comment by somedd** [comment]
@Dumbs-app 1.1.3에서 반영됩니다~!
