### ISSUE TITLE
[어드민] 2차어드민 - 가게정보 > 이미지 순서변경 (드래그앤드랍) 적용건

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#83]
[요청내용]
![Image](https://github.com/user-attachments/assets/03158007-463c-4c94-8955-bade2b4bd668)
가게정보 > 가게 이미지를 드래그앤드랍으로 순서 변경하도록 요청드립니다!

@heyman333

**Comment by heyman333** [comment]
@Dumbs-app 수정완료

**Comment by Dumbs-app** [comment]
확인 완료했습니다! 빠른 대응 감사합니다~~ㅠㅠㅠ!!!
