### ISSUE TITLE
[iOS] ios버전 이슈 수정

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#87]
[개선사항]
ios낮은 버전에서도 다운로드 되도록 세팅 필요

**Comment by somedd** [comment]
@Dumbs-app 지혜님~! 이거 확인해봤는데.. 현재 코드가 17기준으로 작성되어있는 부분이 좀 있어서 17로 유지하는게 어떨까요? https://developer.apple.com/kr/support/app-store/ 실제로 많이 쓰지도 않고있어서ㅠㅠ

**Comment by Dumbs-app** [comment]
@somedd 님 호ㅠㅠㅠ그렇군요 넵넵 그럼 일단 인지하고 있을게용!! 확인 감사합니다~!
