### ISSUE TITLE
[iOS] 쿠폰 사용 후 바로 사라지지 않는 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#89]
### 재현상황 1
1.홈리스트에서 쿠폰다운로드 완료
2. 쿠폰함에서 쿠폰 사용(직원확인) 완료
3. [이슈내용] 홈리스트에 ‘쿠폰확인‘ 버튼 계속 노출됨
4. [이슈내용] 쿠폰확인 버튼 클릭 시 바코드 재노출됨

-> 직원확인 완료된 쿠폰은 그 즉시 홈/쿠폰함/상세페이지에서 모두 미노출처리 필요합니다

### 재현상황 2
1. 홈 > '전체' 탭에서 쿠폰다운로드 및 직원확인 완료
2. '이태원' 탭으로 이동시 해당 쿠폰 계속 노출됨
3. 페이지 리프레시 시 쿠폰 미노출처리됨

-> 직원확인 완료된 쿠폰은 그 즉시 홈/쿠폰함/상세페이지에서 모두 미노출처리 필요합니다

**Comment by somedd** [comment]
@Dumbs-app  1.1.3에서 반영됩니다~!
