### ISSUE TITLE
[어드민] 1차어드민 - 지역선택뷰 추가

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#9]
1차어드민에서 업체승인 시 지역 선택 뷰 추가

**Comment by 3d3nch01** [comment]
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=2639-48921&node-type=FRAME&t=DKUVsMoVrHIJ6nmV-11

### 추가 사항



![Image](https://github.com/user-attachments/assets/6b5eac95-239e-4332-af31-7fe9311e70e9)

1. 지역 정렬
2. 지역 드롭다운 추가 (디폴트: 사용자가 입점 신청 시 선택한 지역)
3. 드롭다운 펼침 추가 (기본 UI 사용 부탁드립니당)



![Image](https://github.com/user-attachments/assets/6ae24c48-d2db-4d22-bdf4-7db339899fea)

1. 사용자가 입점 신청 시 입력한 주소가 텍스트로 노출됩니다.

**Comment by 3d3nch01** [comment]
@Dumbs-app 요 이슈는 캔슬처리 부탁드립니당

**Comment by Dumbs-app** [comment]
#42 이슈로 통합처리하게되어 클로즈합니다
