### ISSUE TITLE
[App] 로그를 심자 - 홈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#91]
@whtjdhks3837 님 @somedd 님
덤즈 앱 홈 영역 [로그설계서](https://docs.google.com/spreadsheets/d/11P6vD-V3JMhlR7cr1ijuj8jN9heDKhFDlGGF2lPNunM/edit?gid=1608698981#gid=1608698981) 전달드립니다!
애매한 부분 언제든 편하게 논의주세요!
혹시 안드/ios 이슈 분리 필요하다고 생각되시면 말씀 주세용~!

<google-sheets-html-origin><style type="text/css"></style>
화면 | 이벤트 정의 (발생시점) | 플랫폼 | screen name | event name | event type | data | 비고
-- | -- | -- | -- | -- | -- | -- | --
덤즈 메인 홈 | 메인홈 진입 | Native | dumbs_home | home | pageview |   |  
덤즈 메인 홈 | 상단 지역 탭 클릭 | Native | dumbs_home | region | click | item_kind: ‘button’region: {region id}item_horizon_index: {지역 순서}region_name: {지역명} |  
덤즈 메인 홈 | 업체 카드 클릭 | Native | dumbs_home | store card | click | item_kind : 'card'item_id : {업체 id}item_name : {업체 이름} ex) '언더그라운드'item_genre : {업체 장르} ex) '힙합'item_admission : {무료입장 여부}item_open : {오픈 여부} |  
덤즈 메인 홈 | 업체 카드 like 클릭 | Native | dumbs_home | club_like | click | item_kind : ‘button’button_name : ‘like’item_id : {업체 id} item_name : {업체 이름} |  
로그인 모달 | 업체 카드 like 클릭 | Native | dumbs_home | login_modal | pageview | entry : {screen_name}_{event_name} ex) dumbs_home_club_like, dumbs_home_coupon_click ...item_kind : ‘modal’ |  
쿠폰 다운로드 클릭 | Native | dumbs_home |  
로그인 모달 | 카카오톡 로그인 클릭 | Native | dumbs_home | login_kakao | click | item_kind : ‘button’button_name : ‘login_kakao’ | 여기도 엔트리 정보 같이 수집 가능할까요?
로그인 모달 | 이메일 로그인 클릭 | Native | dumbs_home | login_email | click | item_kind : ‘button’button_name : ‘login_email’
로그인 모달 | 더 둘러보기 클릭 | Native | dumbs_home | login_cancel | click | item_kind : ‘button’button_name : 'cancel'
로그인 모달 | 회원가입 클릭 | Native | dumbs_home | login_join | click | item_kind : ‘button’button_name : 'join'
덤즈 메인 홈 | 쿠폰클릭 | Native | dumbs_home | coupon_click | click | item_kind : ‘button’item_name : {노출된 쿠폰 이름} ex) ‘최대 15% 할인 쿠폰 받기’item_id : {쿠폰이 노출된 업체 id} |  
덤즈 메인 홈 | 쿠폰확인 클릭 | Native | dumbs_home | coupon_barcode | click | item_kind: : 'button'button_name : '쿠폰확인'item_name : {노출된 쿠폰 이름} ex) ‘최대 15% 할인 쿠폰 받기’item_id : {쿠폰이 노출된 업체 id} |  
덤즈 메인 홈 | 쿠폰 모달 | Native | dumbs_home | coupon_modal | pageview | "item_kind : 'modal'item_name : {노출된 쿠폰 이름} ex) ‘최대 15% 할인 쿠폰 받기’item_id : {쿠폰이 노출된 업체 id} |  
덤즈 메인 홈 | 쿠폰 모달 | Native | dumbs_home | coupon_modal | pageview | "item_kind : 'modal'item_name : {노출된 쿠폰 이름} ex) ‘최대 15% 할인 쿠폰 받기’item_id : {쿠폰이 노출된 업체 id} |  
덤즈 메인 홈 > 쿠폰모달 | 쿠폰 다운로드 클릭 | Native | dumbs_home | coupon_download | click | item_kind: : 'button'button_name : '쿠폰 다운로드'item_name : {노출된 쿠폰 이름} ex) ‘최대 15% 할인 쿠폰 받기’item_id : {쿠폰이 노출된 업체 id} |  
하단탭 | 하단탭 클릭 | Native | dumbs_bottom_tab | bottom_tab | click | "item_kind: : 'button'button_name : {HOME}button_name : {EVENT}button_name : {COUPON}"button_name : {MY}" |

**Comment by somedd** [comment]
@Dumbs-app 1.1.5에서 반영됩니다 :)
