### ISSUE TITLE
[App][iOS] 공연상세 > 유의사항 미등록 시 인포아이콘만 노출되는 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#92]
### 이슈내용
![Image](https://github.com/user-attachments/assets/c4d07f71-c79e-4a46-ab57-c4fb19936b25)
공연상세에 유의사항이 미등록 된 경우 느낌표 아이콘만 노출되는 이슈

### 개선사항
유의사항 내용이 입력되어 있는 경우에만 `느낌표아이콘+내용`이 함께 노출되어야 합니다!

@somedd

**Comment by somedd** [comment]
@Dumbs-app 1.1.4 에서 반영됩니다 :)
