### ISSUE TITLE
[어드민] 공연 생성하기 > 음악장르 추가

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#94]
<img width="720" alt="image" src="https://github.com/user-attachments/assets/e31726d7-d943-46b4-be9a-832142f391ee">

### Figma Link

https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3415-155211&node-type=frame&m=dev

공연/파티별 장르가 추가되었습니다.
추후 앱에서 필터링 가능하도록 (기타는 기타로만 필터링) 내려줄 예정인 듯 합니다.

**Comment by 3d3nch01** [comment]
@Dumbs-app 에딧 완료했습ㅁ니다~
혹시 기존에 업로드된 파티 공연은 모두 기타로 내려주나요? 아님 장르 태그되지 않은 상태??

**Comment by Dumbs-app** [comment]
> [@Dumbs-app](https://github.com/Dumbs-app) 에딧 완료했습ㅁ니다~ 혹시 기존에 업로드된 파티 공연은 모두 기타로 내려주나요? 아님 장르 태그되지 않은 상태??

@txtart 님 의견주실 수 있을까요?
기존에 업로드 된건 장르정보를 아예 내려주지않는 (미노출) 게 나을것 같은데 가능할까욧

**Comment by Dumbs-app** [comment]
음악장르 최종버전 [가이드](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3415-155211&t=gk43UdGmAsv7vxRc-1)에 업데이트 해두었습니다.
- 힙합
- R&B
- 팝
- EDM
- 테크노
- 하우스
- BASS (신설)
- 트랜스 (신설)
- 덥스텝 (신설)
- K-POP (순서조정)
- 기타

@heyman333 @txtart 참고 부탁드리겠습니다!

**Comment by Dumbs-app** [comment]
확인 완료! 감사합니돠
