### ISSUE TITLE
[App][AOS][iOS] 공연상세 > 음악장르 노출 데이터 변경 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_phase2#99]
### 요청배경
https://github.com/Dumbs-app/Dumbs_phase2/issues/94#issue-2637179046
- 원래 '테크노' 장르의 클럽에서 '하우스' 공연을 하게 되는 케이스가 있음
- 공연 생성시 가게정보와 별도로 음악장르를 설정하도록 스펙 추가되었음 (231107)
- 따라서, 앱의 공연상세에 노출되는 음악장르 값이 가게정보 데이터가 아닌, 공연정보 데이터로 변경 필요함

### 요청영역
해당 영역에 `가게정보 음악장르`가 아닌 `공연정보 음악장르` 로 데이터 변경

![Image](https://github.com/user-attachments/assets/6ec1a574-cf70-424d-a1e7-db177352350f)

**Comment by somedd** [comment]
@Dumbs-app 1.1.5에서 반영됩니다 :)

**Comment by whtjdhks3837** [comment]
@Dumbs-app android 수정 완료했습니다
